#!/bin/bash

CARDANO_NODE_USER_HOME=$HOME
if [ -f ${CARDANO_NODE_USER_HOME}etc/genesis.json ]; then
  GENESIS_FILE=${CARDANO_NODE_USER_HOME}etc/genesis.json
fi

if [ -f ${CARDANO_NODE_USER_HOME}etc/topology.json ]; then
  CARDANO_NODE_TOPOLOGY_FILE=${CARDANO_NODE_USER_HOME}etc/topology.json
fi

if [ -f ${CARDANO_NODE_USER_HOME}etc/config.json ]; then
  CARDANO_NODE_CONF_FILE=${CARDANO_NODE_USER_HOME}etc/config.json
  CARDANO_NODE_CONF_TYPE="json"
elif [ -f ${CARDANO_NODE_USER_HOME}etc/config.yaml ]; then
  CARDANO_NODE_CONF_FILE=${CARDANO_NODE_USER_HOME}etc/config.yaml
  CARDANO_NODE_CONF_TYPE="yaml"
fi
if [ -f ${CARDANO_NODE_USER_HOME}etc/secrets/node_secret.yaml ]; then
  CARDANO_NODE_SECRET_FILE=${CARDANO_NODE_USER_HOME}etc/secrets/node_secret.yaml
  CARDANO_NODE_NODE_TYPE="pool"
  CARDANO_NODE_POOL_ID=$(grep 'node_id' ${JORM_SECRET_FILE} | awk '{print $2}')
else
  CARDANO_NODE_NODE_TYPE="relay"
fi

: ${CARDANO_NODE_DB_PATH:=${CARDANO_NODE_DB_PATH:-${CARDANO_NODE_USER_HOME}/storage/}}
: ${CARDANO_NODE_PORT:=${CARDANO_NODE_PORT:-9000}}
: ${CARDANO_NODE_SOCKET_PATH:=${CARDANO_NODE_SOCKET_PATH:-/var/run/cardano/cardano-node.sock}}

: ${CARDANO_NODE_MAX_STARTUP_TIME:=${CARDANO_NODE_MAX_STARTUP_TIME:-20}}
: ${CARDANO_NODE_MAX_FAULT_UPTIME:=${CARDANO_NODE_MAX_FAULT_UPTIME:-600}}
: ${POOLTOOL_MAX_BLOCK_DELTA:=${POOLTOOL_MAX_BLOCK_DELTA:-5}}

export CARDANO_NODE_SOCKET_PATH=${CARDANO_NODE_SOCKET_PATH}
