#!/bin/bash

: ${JORM_REST_API_PROTOCOL:=${JORM_REST_API_PROTOCOL:-http}}
: ${JORM_REST_API_ADDRESS:=${JORM_REST_API_ADDRESS:-localhost}}
: ${JORM_REST_API_PORT:=${JORM_REST_API_PORT:-3100}}
: ${JORM_REST_API_ENDPOINT:=${JORM_REST_API_ENDPOINT:-api}}
if [ -z ${JORM_REST_API_URI+x} ]; then
  JORM_REST_API_URI=${JORM_REST_API_PROTOCOL}://${JORM_REST_API_ADDRESS}:${JORM_REST_API_PORT}/${JORM_REST_API_ENDPOINT}
fi